version: '3'
services:
  lunarium:
    image: lunarium
    build: .
    deploy:
      replicas: 1    
    ports:
      - "44071:44071"
    volumes: 
      - /opt/lunarium/data/:/home/lunarium/.lunarium/
